name: Lab10 CI

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  ci:
    name: Python Lint & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Run Flake8
        run: |
          flake8 scripts/ --max-line-length=88 --extend-ignore=E203,W503

      - name: Run Pytest
        run: |
          pytest -v

  docker:
    name: Build & Push Docker (GHCR)
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        id: meta
        run: echo "owner=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.owner }}/weather-classification-mlops:latest
            ghcr.io/${{ steps.meta.outputs.owner }}/weather-classification-mlops:${{ github.sha }}