name: Deploy MLflow to Render

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/mlflow-deploy-render.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy for MLflow service
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_MLFLOW_SERVICE_ID: ${{ secrets.RENDER_MLFLOW_SERVICE_ID }}
        run: |
          if [ -z "$RENDER_API_KEY" ] || [ -z "$RENDER_MLFLOW_SERVICE_ID" ]; then
            echo "Render secrets not set (RENDER_API_KEY, RENDER_MLFLOW_SERVICE_ID). Skipping deploy." && exit 0
          fi
          curl -s -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            https://api.render.com/v1/services/$RENDER_MLFLOW_SERVICE_ID/deploys \
            -d '{}'
          echo "Render deploy triggered for MLflow service: $RENDER_MLFLOW_SERVICE_ID"